### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#1]
For the Amsterdam foodcoop, we could really use a Dutch translation! With the internationalisation work done (with the English translation), this should be a managable task.

See the files in `config/locales/` .

**Comment by wvengen** [comment]
Trying out [localeapp](http://www.localeapp.com/) now on [this project](http://www.localeapp.com/projects/4601).

**Comment by wvengen** [comment]
localeapp seems to work
next step: setup a test instance for translators connected to localeapp with data such that all texts are accessible

**Comment by wvengen** [comment]
See [Translation](https://github.com/wvengen/foodsoft/wiki/Translation) on the wiki for more information. Translators can use localeapp to translate, with a dedicated foodsoft instance that pulls translations directly from localeapp.
Pending: script to split single files from localeapp into our file structure so that we can merge cleanly it into the repository + links to switch translation in the foodsoft instance (#23).

**Comment by dokterbob** [comment]
When opening the project at locale app it seems as though German is the source language instead of English. As I don't feel much like taking a dictionary while translating and we ought to think of a more global contributing community; shouldn't the source lang be changed to English instead?

If so; gimme a poke, I'll create a separate ticket and explain what needs to be done. (It's better having multiple small tickets rather than few jumbo one's that never get fixed.)

**Comment by wvengen** [comment]
The original texts are German. This has mostly been translated to English, but it can really use some improvement. For now, I consider the German to be leading. When English has been improved, let's switch to that by default.
Some new functionality is only available in English, that's why German has some missing strings.

The current main translators have developer access and can change the source language - which works as long as they don't work at the same time.

**Comment by dokterbob** [comment]
Okay. In that case I'd like to propose English translations as being the main priority as this would enable a lot of other people (including Dutchies) to easily translate to their native language.

For one, I would love to translate from English to Dutch but am not comfortable doing it from German to Dutch or English.

**Comment by fsmanuel** [comment]
closed in favor of https://github.com/foodcoops/foodsoft/issues/156
