### ISSUE TITLE
simplify and cleanup interface

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#10]
The current user-interface contains a lot of functionality, and we fear that most of that would be confusing for a new user. For now, we don't need that anyway in foodcoop-adam. It would be enough to remove the user-interface elements, not necessarily the underlying functionality.

Feature branch: [rails3-uicleanup](https://github.com/wvengen/foodsoft/tree/rails3-uicleanup) (to be created)
- home screen cleanup (incl. dashboard)
- remove wiki
- remove messaging
- remove applepoints / work items
- language preference in user settings (issue #23)
- any more?

When this is done, add admin section where admins can de/-activate user-interface elements as commented below by @fsmanuel.

**Comment by fsmanuel** [comment]
maybe it makes more sense to add some settings like not_displayed_ui_elements = ['wiki', 'messaging', 'applepoints'] and add a helper should_dispaly?('wiki'). we could add an admin section where admins can de-/activate them.

**Comment by Cor-Jan** [comment]
remove "directly to" shortcuts
remove "foodcoop" menu item completely?
remove link to the front website (foodcoop.nl) top right
temporarely remove the "help" button until something is there that can be used by non-techies

**Comment by wvengen** [comment]
Thanks @fsmanuel, that's a great idea to keep the code usable by multiple coops.
I think, for now, we'd like to remove it in our own branch, to focus on creating a user-interface that works best for us. When we have something to work with, I'd love to add functionality to choose between ui elements like you suggest (and thanks for the practical hints, btw).

**Comment by Cor-Jan** [comment]
some visualisation of the cleanup proposal from current to dashboard with menu on top until menu half erased, half transferred to the admin page

![screen shot 2013-05-11 at 11 52 50 pm](https://f.cloud.github.com/assets/3144698/492165/3da13d06-ba85-11e2-8252-533ac15fdee1.png)

![screen shot 2013-05-11 at 11 53 01 pm](https://f.cloud.github.com/assets/3144698/492164/3da0df0a-ba85-11e2-85c9-847205ba6a58.png)

![screen shot 2013-05-11 at 11 53 10 pm](https://f.cloud.github.com/assets/3144698/492163/3d975d68-ba85-11e2-8ff9-b626864f1ced.png)

![screen shot 2013-05-11 at 11 56 59 pm](https://f.cloud.github.com/assets/3144698/492167/bf1e1d04-ba85-11e2-8b69-bb9fe2157b03.png)

**Comment by wvengen** [comment]
Mostly done in rails3-uicleanup. The navigation bar is hidden by default, and only shown when admin-functionality is accessed. Pending:
- restructure navigation bar (so that one recognises where to go for what task)
- language preference in profile (not urgent, since we have a chooser top right) (#23)

**Comment by wvengen** [comment]
These are all implemented now in foodcoop-adam-new. I'm sure more ui improvements will come up, we can open a separate bug / separate bugs for that, as well as discuss on the mailing list.
