### ISSUE TITLE
[vokomokum] synchronize order amounts

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#106]
Vokomokum's existing ordering system needs to receive totals of the fresh orders. For every order cycle, there are totals for "Groente", "Kaas" and "Misc.".

How to get totals from foodsoft into the Vokomokum ordering system?

The plan is as follows:
- [x] After each change in what a member received, the change is submitted to the existing ordering system. This could be done, for example, with `GroupOrder#update_price!`.
- [x] only send updates when order is finished (to avoid not really needed roundtrip when members are ordering); then send all amounts when order is closed.
- [x] In orders overview, add vokomokum fresh csv to menu "Combined PDF"
- [x] Upload sum of group order prices of all finished_but_not_closed orders instead of single order
- [ ] Test cases for the important (corner- and normal) cases. If only plain text, @wvengen can turn them into rspec code.
- # 114: Handling account balance
- #115: Handling errors gracefully
- #131: Group export_amounts CSV by type
  - Each supplier could get a field indicating whether its orders are accounted for in "Groente", "Kaas" or "Misc.", or we just use one of the fields.

**Comment by wvengen** [comment]
For code, see the vokomokum plugin in [`lib/foodsoft_vokomokum`](https://github.com/foodcoop-adam/foodsoft/tree/master/lib/foodsoft_vokomokum). Uploading totals is done using [`#upload_amounts`](https://github.com/foodcoop-adam/foodsoft/blob/master/lib/foodsoft_vokomokum/lib/foodsoft_vokomokum/remote.rb#L30). Pass a hash of `{ordergroup_id => sum}`s to it, like this [csv export](https://github.com/foodcoop-adam/foodsoft/blob/5958a9c3ac53aef766181c8c06da4cbb067aeafa/lib/foodsoft_vokomokum/app/controllers/vokomokum_controller.rb#L36); or to export the total of the current user's unsettled orders:

``` ruby
ordergroup = current_user.ordergroup
group_orders = ordergroup.group_orders.includes(:order).where(orders: {state: ['open', 'finished']})
amounts = {ordergroup.id => group_orders.sum(:price)}
```

**Comment by tg-x** [comment]
We also need to upload amounts after changing the order from open to finished.

The export_amounts CSV should group the orders by type, as that's the way the manual upload expects it.

**Comment by tg-x** [comment]
As I see Order.finish calls GroupOrder.update_price!, so that should already work.

**Comment by wvengen** [comment]
Functionality is done! I've tested opening, closing and settling an order, as well as updating order amounts when the order is closed. All works! Let's open a new bug for testing if we want to.

As a side note, deleting a closed order also works (updating the dry goods system), but takes a lot of time; a future improvement may be to also do the update once in batch. But, as that's not likely to happen often or even at all, it's ok for now.
