### ISSUE TITLE
Rails Update

### ISSUE THREAD

**Issue by fsmanuel** [foodcoop-adam/foodsoft#11]
https://groups.google.com/forum/?fromgroups=#!topic/rubyonrails-security/61bkgvnSGTQ

we should update to 3.2.11 or better 3.2.13

**Comment by wvengen** [comment]
I think this is already done in [Gemfile.lock](https://github.com/wvengen/foodsoft/blob/rails3/Gemfile.lock#L140) / 957dbc7202fcd86609af62e910d6e554f184d34f . Thanks for the notice though!
