### ISSUE TITLE
[vokomokum] graceful error handling with dry order system

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#115]
The total amount of member orders is communicated to the vokomokum dry ordering system (by means of the fresh upload form, internally). This may not always succeed, and those cases need to be handled gracefully by foodsoft.
1. Find out what can go wrong
2. Decide how to react
3. Implement sensible responses in foodsoft

Issues:
- [x] What to do when the vokomokum member order is closed and it can't be updated, for example.
- [x] Can we detect errors using the 'direct' vokomokum upload, or do we need to submit csv for that?
- [ ] ...

**Comment by tg-x** [comment]
Error checking only happens during CSV upload, so we do a two-step upload, first using the CSV method. See b948af8336688fce35d24a1e6ccc0aedb80509e7

**Comment by wvengen** [comment]
What's left is presenting errors to the user (as right now they're exceptions). Ajax error handling is most important here.
