### ISSUE TITLE
re-upload productlist

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#13]
when updating a productlist from a supplier foodsoft gives errors for all the products except for products that have new productnames. for that reason to update a productlist the previews productlist is completely deleted and uploaded again. 
we would like that with a second upload of an updated productlist that the productlist in foodsoft is updated by comparing the productlist in foodsoft with the productlist newly uploaded.

solution proposal 

![screen shot 2013-05-09 at 12 31 56 pm](https://f.cloud.github.com/assets/3144698/482359/c1893680-b893-11e2-8fdf-cc4635596ec0.png)

**Comment by wvengen** [comment]
To this end the external database and upload functionality could be merged (as both would do similar things) - which is an open bug at upstream foodcoops/foodsoft#113 planned for its next milestone.
