### ISSUE TITLE
Implementing iDeal for membership fee payment

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#15]
We are going to use Ideal for payments of membership fee from public signup route (there will be also a route for people who want te become a member on the spot during pickup day who will pay with PIN/Eurocard) 
proces:
potential members fill in their emailadress, get an email with an invitation to become a member with link to online membership form. (this is already functional) 

After the form has been entered there should apear an ideal payment. if the ideal payment is confirmed than we wil get an confirmation via xml or email which should activate the member so they can order.

the ruby script for ideal payments with molly/paytor
https://github.com/manuelvanrijn/ideal-mollie

**Comment by wvengen** [comment]
Created branch: rails3-onlinepay
This is a bit of a hack, adding a payment controller and view that creates a financial transaction. This would enable users to pay using iDEAL. I also plan to add a configuration parameter that allows to require a membership fee to place an order (similar to the minimum apples limit).

**Comment by wvengen** [comment]
Done! It would be nice to have a more flexible payment system, perhaps using plugins, so that multiple payment methods could be used.
Configuration variables have been added to enable/disable the membership payment requirement. Online payment user-interface elements are only shown when `config.ideal_mollie` variables are set.

**Comment by wvengen** [comment]
Now this could use some refactoring using transactions at al places (see [code comments](https://github.com/foodcoop-adam/foodsoft/blob/onlinepay/app/controllers/payments_controller.rb) for more details). This would include modifying the database schema, perhaps to include a remote transaction identifier (with consisting of payment supplier + transaction id).

**Comment by wvengen** [comment]
closing in favour of #81
