### ISSUE TITLE
Show products per category instead of per supplier

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#16]
On the member ordering page. If this is hard, a single list with all products would also be an improvement - if the website doesn't become too slow.

At the moment every supplier has a seperate orderlist directly based on their orderlist. 
to order a member has to open a orderlist for every supplier, place the order, close the orderlist en open a new orderlist of the next supplier. if multiple suppliers have the same type of product (e.g. pasta) they are now only available in different list.

solution proposal:
combine the productlists of all suppliers in 1 orderlist, where the products are organized based on categorisation and similar products are next to eachother.

For the orderteam whom select which products will be selected from different suppliers it would be great if they where able to see the productlists organized based on categories so if different suppliers supply pasta that the orderteam can delete the products which are most expensive, lowest in quality, sustainability or taste
- add navigation based on productcategories?

**Comment by wvengen** [comment]
closely related to #19

**Comment by wvengen** [comment]
Actually, this is done in branch feature-group_order_ajax-adam (renamed to beta), which will be merged to master at some point.
