### ISSUE TITLE
create a DEMO account so potential new members can see actual articles with their prize available

### ISSUE THREAD

**Issue by xxaw** [foodcoop-adam/foodsoft#167]
This to draw more members. 
it would be nice to have a demo account where you are inside the ordering module. but not able to actual order articles. After leaving all settings should be set to zero again.
Basically all functionality should be disabled in this account. 
If it can be open always visitors could see actual prizes everyday that would be great

**Comment by wvengen** [comment]
Good idea! It is already possible to set the apple-points ordering stop checkbox in the demo member's ordergroup settings.

Please note that the demo user can also visit the member list and read and write messages.

**Comment by xxaw** [comment]
i think it important when the dashboard is completely disabled, only the
ordering mechanisms should be in place but (of course) not being counted
when processing the orders

so to give full user experience but completely 'sandboxed'

groetjes,

Allard

---

**Comment by wvengen** [comment]
Hmm this may either be a candidate for the [demo plugin](https://github.com/foodcoop-adam/foodsoft/tree/beta/lib/foodsoft_demo) (though this is quite a different use-case, the current demo plugin is for a separate demo-instance with auto-login). Or we could perhaps create a publically-viewable page where it is possible to browse or list the products of the current/last open orders. (A simple (though possibly long) list may even be embeddable in a wordpress site, for example.) What do you think?

**Comment by xxaw** [comment]
Hey,

If I am reading it correctly the demo plugin is a complete working
dashboard with out possibility to actually order or send messages to other
, thats exactly how it should be in my opinion. however aq normal user
account can be closed and then the prices cant be seen. The demo account
should always having access to the latest prices, products and suppliers
and so giving a potential new member a complete feeling

greetz,
Allard de Jaager

---

www: www.all-ard.nl

## mob: +316 5463 2345

**Comment by wvengen** [comment]
The focus of this fork has become getting relevant functionality upstream. If you need this feature, please open an issue with [upstream foodsoft](https://github.com/foodcoops/foodsoft/issues).
