### ISSUE TITLE
[vkmk] Add button to send payment mail

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#169]
Finance needs to send payment mails to members after all orders have been settled. Sending the mails is done by the members system, but the "Account orders" screen is a sensible place to do it from.

Suggestion:
- Add button to accounting index for sending payment mails
- Have button in grey by default
- When all orders are settled, the button becomes blue (`btn-primary`)
- Also a flash message is shown after settling the last order to indicate that mails need to be sent
- When the send-mails-button has been pressed, a sent-at attribute is set to the current time on all settled orders that didn't have that before.
- When all settled orders have a non-null sent-at attribute, the button remains grey.

In this way, after settling all orders, the finance team is naturally reminded to send the mails, while still being able to send them if there is a deviation from the normal ordering routine.
- [x] Add `payment_reminders_sent_at` attribute to `Order`
- [x] Add button for sending payment mails, which waits for a rest-call to the members system
- [x] Handle errors from the members system
- [x] Update `payment_reminders_sent_at` attribute as well
- [x] Only set `btn-default` on button when there are settled orders with a null `payment_reminders_sent_at` attribute and no closed orders (this allows an open order for the next ordering cycle to be present already).
- ~~Show flash message to send payment mails when the above condition is met after settling an order~~

Depends on https://www.assembla.com/spaces/vokomokum/tickets/255

**Comment by wvengen** [comment]
@nhoening

**Comment by wvengen** [comment]
I'm not sure if the last point is actually needed, to show a flash message when the last order was finished. The button should already turn blue. If it was really simple, I'm happy to add it, but it requires more monkey-patching, I'm afraid.
Let's wait until the finance people request this?

**Comment by nhoening** [comment]
sounds good to me!

**Comment by wvengen** [comment]
Thanks! What remains is testing :)

**Comment by wvengen** [comment]
Implemented and tested on branch [acceptance/vokomokum-dry](https://github.com/foodcoop-adam/foodsoft/tree/acceptance/vokomokum-dry).
