### ISSUE TITLE
Stock based coop

### ISSUE THREAD

**Issue by elbotho** [foodcoop-adam/foodsoft#173]
Hey there,
this software looks amazing!
Is there a way to use it for a stock based coop ("Lager-Coop") as well?
(sorry, don't know the right term, but we order food and store it in a room.
All members can come and take as much as they want. No need for individual orders. How do you call that?)

It seems all the db-tables and most functions are already there, but the checkout would have to be altered, right?
What else is needed?

[I'd like to contribute, but I have zero experience with ruby. I could work on the frontend.]

**Comment by wvengen** [comment]
Hi, thanks! Yes, there is support for that as well in [foodcoops/foodsoft](https://github.com/foodcoops/foodsoft) (though not explained in [the video](https://vimeo.com/145927538)). I haven't used it myself in practice though, perhaps it's better asked on the [foodsoft-discuss mailing-list](http://foodsoft.51229.x6.nabble.com/foodsoft-discuss-f5.html). 

[it happens to be that I'm experimenting with a a [React](http://facebook.github.io/react)-based member ordering interface, it that's something you'd like.]

**Comment by wvengen** [comment]
The focus of this fork has become getting relevant functionality upstream. If you need this feature, please open an issue with [upstream foodsoft](https://github.com/foodcoops/foodsoft/issues).
