### ISSUE TITLE
[BUG] Article quantity do not add up to #units-to-order

### ISSUE THREAD

**Issue by antil0pa** [foodcoop-adam/foodsoft#175]
*Follow up to http://foodsoft.51229.x6.nabble.com/problem-updating-foodsoft-adam-td1189.html

After updating to Foodsoft v3.3.9+adam+ß there is a problem of adding articles to the total order. The 
'Everyone' column and the tollerance bar zero out after refreshing the page.

I tested it on again with the foodcoopamsterdam demo on 3 different browser and 2 different machines.

In the screenshot of the interface , it is visible that though some orders should be full, none are marked to be ordered.

![foodsoft](https://cloud.githubusercontent.com/assets/9811268/12765086/29cc3c4c-c9fd-11e5-9513-2749321a46f0.png)

**Comment by antil0pa** [comment]
I found the source of the confusion. The shopping cart function has been added, therefore individual orders are not added to the Everyone column until paid for. This seems logical, But when you add or remove articles it still affects the units-to-order count in the Everyone column. This is only temporary - refreshing the page sets it back to zero. 
This causes conflicts between the units-to-order column and the Amount column, when units-to-order can even show a negative quantity when removing article-units.

**Comment by wvengen** [comment]
I got bitten by this today as well. It's even more confusing after the [amount coloring](https://github.com/foodcoop-adam/foodsoft/commit/100f8351f635b797eec1b1241b0bb8b0c15f324b).
[This is the offending line](https://github.com/foodcoop-adam/foodsoft/blob/beta/app/views/group_orders/_order_article.html.haml#L16) (plus tolerance equivalent). Replacing it by

``` ruby
data_delta[:value_others] = order_article.quantity - \
  group_order_article.group_order_article_quantities.confirmed.sum(:quantity)
```

when the payorder plugin is enabled would do wonders. Haven't been able to do that in a somewhat clean way, though (deface messes up stuff).

**Comment by wvengen** [comment]
I added a workaround for this. Better now?

**Comment by wvengen** [comment]
The focus of this fork has become getting relevant functionality upstream. If you need this feature, please open an issue with [upstream foodsoft](https://github.com/foodcoops/foodsoft/issues).
