### ISSUE TITLE
List articles ordered by everyone in member ordering

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#178]
To fill the boxes, it would be useful to see which products were ordered by others/everyone.
This can be a simple button below _My order_ (top left in member ordering screen), resulting in a flat list.

dutch translation: _Bestelling van allen_ or _Bestelling van iedereen_

**Comment by wvengen** [comment]
![foodsoft_-_my_current_order_-_2016-06-10_14 03 20](https://cloud.githubusercontent.com/assets/503804/15963680/276671b2-2f14-11e6-80be-9bd37226194f.png)

**Comment by wvengen** [comment]
@Tamriel this may not be exactly what you asked for, but would this also work? This page shows the articles ordered by everyone. Wherever there's blue in the bar on the right, something is still needed to complete a box.

**Comment by Tamriel** [comment]
Beautiful.
This fully fulfills my needs :)
What is the meaning of the 'plus' between the blue bar and the number of complete bundles?

**Comment by wvengen** [comment]
That right bar and right box together tell what was ordered by everyone for that article: the blue bar is the final box, while number on the right box indicates how many are already full. So the bottom row reads "4 units (+3 extra) are in the remaining box to be filled, and there are 2 boxes already full".

**Comment by wvengen** [comment]
And great, I'll release a new version in this fork soon.
