### ISSUE TITLE
login with email address

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#18]
at the moment people have to thinkup and use a nickname to login. this makes thinks more complicated, especially for people who do not use computers very much.

solution proposition:
- login with emailadress instead of nickname
- (allow to) show full name where user is displayed in ui; this could be a helper method which can be overridden in a plugin

**Comment by wvengen** [comment]
Yes, I think the presence of a username can take 'psychological space' for users, an emailaddress would be a good alternative.

We need a display name for users (e.g. in "who opened an order", "who sent me a message", or "who signed up for this task"), and a userid for internal usage. The username must be unique, so in some cases something like a street name or locality needs to be added, or a second name, to distuingish between people with the same name.

One reason why this may not be good idea, is if there are people who do not want to share their full names but are comfortable with a username. This is currently an option in the user profile.
Question to people from other coops: is this relevant to you?

**Comment by Cor-Jan** [comment]
for me, knowing eachothers name is something that contributes to the contact between people. if they know someones name through messages through the system it is easier to connect. if you only know someone's nickname one cannot tell who is who.

**Comment by wvengen** [comment]
Suggested solution:
- Use e-mail address for login (get rid of usernames)
- Use somewhat configurable way (e.g. a method of `User`) to get a user's display name. Privacy-aware installations could use a userid, email address (or even a username); others could use full names, for example.

Question for other foodcoops: Is there a need for a username? If not, we can get rid of it. If so, we could give configurable options for foodcoops to choose what fits them.

**Comment by wvengen** [comment]
implementation done, waiting for foodcoops#189 to be merged

**Comment by wvengen** [comment]
fixed by foodcoops#189
