### ISSUE TITLE
check-in delivered articles / receive screen

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#2]
When products have arrived, they need to be counted/weighted to see if it corresponds to what was ordered.
1. Redistribute over the users who have ordered the products (see #3)
2. Compare with invoice, and update/change invoice (see #?)

In foodsoft there is an option called "deliveries", but that's something else (obtaining stock articles). Current functionality is part of the "balancing" screen, but this also contains financial details which are confusing when only checking in products.

Some screens to give an idea how it would work for veggies and for wholesale products.

![screen shot 2013-05-09 at 12 54 56 pm](https://f.cloud.github.com/assets/3144698/482475/da74a8dc-b898-11e2-8c97-4a9b0f608ac9.png)
![screen shot 2013-05-09 at 12 54 46 pm](https://f.cloud.github.com/assets/3144698/482476/da8a9692-b898-11e2-9718-f6397bc80ccf.png)
![screen shot 2013-05-09 at 12 54 33 pm](https://f.cloud.github.com/assets/3144698/482477/da98faac-b898-11e2-90b2-522401811078.png)

see also https://github.com/foodcoops/foodsoft/issues/103#issuecomment-19479133 about checking in products

**Comment by wvengen** [comment]
This will be tackled by the receive screen. Currently only wholesale is taken into account, fresh is for later (sorry).

When partial wholesale packs are delivered, the current approach in some foodcoops is to set unit_quantity to one, and enter how many single packages were delivered. To reduce development effort, we can take that approach (there is a new edit button in the receive screen to edit the order article properties). As this is not expected to happen often, I think we can live with that for now.

What shall we do with the right column +1/-1/v? Number of extra wholesale packs than ordered ~~, or number of single packages that will not be assigned to member orders?~~

**Comment by wvengen** [comment]
will be implemented by foodcoops#222
