### ISSUE TITLE
Hide ordergroup when all its users are removed

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#20]
If a member is deleted and he is the only member is this ordergroup, his ordergroup should also be deleted from the system. At the moment we can delete users until a ordergroup has zero members and still the ordergroup is in the database and that clutters the database.

proposal solution:
if all users are deleted from an ordergroup the ordergroup commits suicide.

**Comment by wvengen** [comment]
It may still be nice to have a record of the past.
What is your need here? Clarity, conciseness? In that case we could just hide them from view (except in admin sections used to view accounts and finances).

**Comment by Cor-Jan** [comment]
hiding past ordergroups/households is even better so we can use it for historical data about orders.
