### ISSUE TITLE
creation of a new user and ordergroup together

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#21]
A user without a household does not make sense. The flow of the user-interface should offer a user to join an existing or create a new ordergroup when creating a new user.

(Original description: to create a user is to create a household. that user will become the pater familia who can add other household members into household.)

**Comment by fsmanuel** [comment]
Think about the Workflow. If i just want to join a household it shouldn't create one for me. If the household owner can create that new user (me) it is ok...

**Comment by Cor-Jan** [comment]
the household owner can invite new users, that is already a function in foodsoft. 
![screen shot 2013-05-11 at 12 27 43 pm](https://f.cloud.github.com/assets/3144698/491426/4ac62adc-ba26-11e2-83f3-d4e2a50e45e9.png)
![screen shot 2013-05-11 at 12 27 58 pm](https://f.cloud.github.com/assets/3144698/491427/4dd627ea-ba26-11e2-8b45-c437c8d7597e.png)

to join a household from new user perspective is much more complex.

**Comment by wvengen** [comment]
If this issue is exactly what the title says, it will probably be marked invalid - @fsmanuel's comment.
Is it that you would like to have a signup process for new users that do not fit into an existing household? Or a signup flow that helps users find out if they'd like to join an existing household, or start their own?

**Comment by Cor-Jan** [comment]
i would like that with creating a new user, automatically a household (ordergroup) is created so this has not to be done manually and so that it is not possible to have a user that cannot order.
what is understood that the ideal transaction to pay for the membership fee is for the creation and activation of a household. i do not see the point of creating a user without household (ordergroup). if someone does, please let me know

**Comment by wvengen** [comment]
Already implemented in branch rails3-selfsignup: a user can signup for an account and create an ordergroup at the same time. When configured, a membership fee must be payed before ordering is possible.

There are such things as separate users and ordergroups (or households), they aren't the same. That is why the software architecture needs this distinction. The users doesn't need to be aware of that when creating an account. All he needs to know if he wants to order by himself (create ordergroup), or do that together with one or more existing members (join existing).
