### ISSUE TITLE
Temporary combine both "amount" and "tolerance" numbers 

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#25]
at the moment there are 2 columns for both "amount" and "tolerance" in the order screen. it is not clear what it means and triggers confusion. as pragmatic solution combine the 2 numbers into one and just show how much the member wants to order and as tolerance.

later find a visualisation that can display what you know for sure to get etc.

![screen shot 2013-05-12 at 12 10 49 am](https://f.cloud.github.com/assets/3144698/492182/afcdef30-ba87-11e2-81d0-727def286a85.png)

**Comment by wvengen** [comment]
done in uicleanup
