### ISSUE TITLE
Hide "credit" field in Orders

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#26]
it shows how much credit the member has but we do not work with prepaid. it does not seem to have a function in our case and takes up screen space and mental space.
therefore: hide the "credit" field

![screen shot 2013-05-12 at 12 14 37 am](https://f.cloud.github.com/assets/3144698/492186/5ca5784a-ba88-11e2-9d74-202391cce30b.png)

**Comment by wvengen** [comment]
I think the ordergroup's balance should still be visible, so that members can see whether they have payed or not. Solution: add total to open and unaccounted orders + somewhere add account balance (at bottom). Then these amounts blend into the user-interface.

**Comment by wvengen** [comment]
Currently in branch uicleanup we don't use this page (only dashboard for open orders + group_order archive). For foodcoop-adam, this is solved now. Only the total amount of finished_but_not_closed orders still needs to be shown.
