### ISSUE TITLE
Hide "order" information in order screen

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#27]
the order information shows 
- who created the order (not relevant)
- last ordered (not relevant)
- credit (not relevant without prepaid)
- when order ends is shown on the right of the screen
- name of supplier on top is not relevant when combining all the suppliers into 1 orderlist 
- minimum amount is not relevant when combining all the suppliers into 1 orderlist

it takes 1/3 of the screen!

So: hide it completely

![screen shot 2013-05-12 at 12 18 05 am](https://f.cloud.github.com/assets/3144698/492187/bd10123a-ba88-11e2-8de1-ce88691026da.png)

**Comment by wvengen** [comment]
fixed by f25b6222c6d18faed3bf361e21632c5e265d65f1.
