### ISSUE TITLE
Do not show "missing units" when product is ordered by piece (no combi-order) 

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#28]
now if a product is ordered per piece the system shows a "1" in the "missing units" column which is confusing for members.

Solution proposition:
do not show any number in the missing item column if the products can be ordered per 1 piece

![screen shot 2013-05-12 at 12 52 08 am](https://f.cloud.github.com/assets/3144698/492230/a9687d30-ba8d-11e2-9bb7-2fbe8340a5cc.png)

**Comment by wvengen** [comment]
done in new uicleanup
