### ISSUE TITLE
more detailed/structured addresses

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#29]
Replace textfield "adress" with zipcode and housenumber in member profile.

Now the household is created by the adress field, which is a text field. this text field can be used to insert rubbish. with replacing adress field with a zipcode field where potential members can only enter 4 digits in the first field and two letter in the 2nd field and letters in the 3rd field we always have a unique adress. 
combined with the postcode.nl API we can lookup the full adress automatically.

![screen shot 2013-05-12 at 1 02 04 am](https://f.cloud.github.com/assets/3144698/492237/e2958980-ba8e-11e2-911c-ee7768021d9d.png)
![screen shot 2013-05-12 at 1 03 02 am](https://f.cloud.github.com/assets/3144698/492242/0665be20-ba8f-11e2-8d32-db3e4f99008d.png)

**Comment by wvengen** [comment]
Would be nice to have.
For now, add full locations fields to ordergroup (street, number, opt. number suffix, zipcode, city, state, ...) - perhaps briefly check geocoding modules for commonly used fields. Same would be useful for supplier address.
Not urgent right now, only until we start actually doing something with the information.
