### ISSUE TITLE
(re)distribute incoming products when delivered != ordered

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#3]
When the delivered products are less, more or different from the products ordered, how to cope with that?

There are 4 scenarios:
1. too much
2. too little
3. not delivered
4. not ordered

**Comment by wvengen** [comment]
1. too much - redistribute over member orders' tolerance (optional), rest to stock (see foodcoops#35)
2. too little - recompute member distribution
3. not delivered - set result to zero and recompute member distribution
4. not ordered - add product to order and enter amount delivered, all to stock

Some foodcoops may not want to use stock (yet), in that case "to stock" means either doing nothing (leaving a difference between ordered and member orders), or assigning rest to a special ordergroup belonging to the foodcoop.

**Comment by wvengen** [comment]
mostly implemented in fresh-flow (not: rest to stock)

**Comment by wvengen** [comment]
This is done in the receive screen. Closing the issue here. Pending is putting the remainder in stock, but that's out of scope for the current issue.
