### ISSUE TITLE
Create a very extended central product catalogue

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#31]
at the moment we have a catalogue of products that has only the most necessary information to order. but we cannot see anything how the product is different from other products, if it fits into our diet, 

Central database with all products of all wholesalers for retail starting with the netherlands
add assortment of farmers and when, what is available and where. 
- Find products better
- filtering see only relevant products (fits your diet; check allergens, 
- helps you get enough nutrition when on a diet to compensate
- compare products within catalogue (e.g. different types of chocolate) based on sustainability,etc
- feedback on taste etc.

faceted searching/browsing

faceted classification 
classify based on:
based on origin: what plant/animal it comes from and which part from that species it is.
based on use;  snack, drinks, candy 
based on nutrition, 

based on eCl@ss/UNSPSC(OWL)
http://www.heppnetz.de/projects/

all ingredients
allergens
(deduce if a product is vegetarian or vegan or not)

process description footprint LCA analyses for every
production
processing (silvur on the raisins, heating of products)
packages (energy used for production, function to keep it longer, recyclebleness?
transport 

value
in what way does it contribute, is it better then the same product of other suppliers

being able to scan a barcode and go to the productpage to see product info

this catalogue we can build ourselves, another option is to use an existing catalogue software. an existing catalogue which is used for rich data for hardware (computer, printers etc.) is icecat; which is used by 20.000 webshops and shops all over the world. which is also available open source (written in perl)

**Comment by fsmanuel** [comment]
I would recomment to build a new service with a strong API. This functionality shouldn't be in the foodcoop software but the foodcoop software should query the API.

That way we separate the two complexities and can offer a great service which is maintainable. It is a more flexible solution and we have less blockers for releases.
@wvengen and @bennibu what do u both think about it?

**Comment by Cor-Jan** [comment]
sounds great!

**Comment by wvengen** [comment]
I see a number of features:
- a central database with all products
- rich product descriptions (including structured fields as allergies, ingredients, nutritional value, etc.)
- selection of products from central database for use in a foodcoop (possibly with the help of policy rules)
- product reasoning / complex searches (e.g. "is this product vegan (reasoned from its ingredients)?" )
  Some functionality may need to be exposed from foodsoft (e.g. extra product information - perhaps a link to an external page is enough, or rendered into text). Also faceted browsing in foodsoft would be useful.

Separating a full central database from a foodsoft instance would be good (like the current external database approach, perhaps in a more general way). Product reasoning is something that would belong elsewhere too.
