### ISSUE TITLE
set foodcoop address and other details (amsterdam)

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#33]
in the orderform that goes to suppliers, the information of the supplier is there, the info of the foodcoop is not there (adress, contact info, etc). is this something that has to be added or is there a form that has to be filled in?

![screen shot 2013-05-17 at 12 11 55 pm](https://f.cloud.github.com/assets/3144698/517376/5e9bb55e-bedb-11e2-8f0d-f99a2d62132c.png)

**Comment by wvengen** [comment]
These still need to be configured in `config/app_config.yml`. Please see [config/app_config.yml](https://github.com/wvengen/foodsoft/blob/foodcoop/config/app_config.yml.SAMPLE) for details that need to be filled in. We still need to look at `name`, `contact`, `price_markup` and `membership_fee` - feel free to send me an email/message with these details.

**Comment by Cor-Jan** [comment]
shall i just edit the details?

FoodCoop Amsterdam
Admiraal de ruijterweg 150
1056 GV Amsterdam
bestel@foodcoop.nl  (contact for suppliers)

Markup: 5%
membership fee: 35 euro

**Comment by wvengen** [comment]
Done in the production config file at order.foodcoop.nl.
