### ISSUE TITLE
Up to date tests

### ISSUE THREAD

**Issue by dokterbob** [foodcoop-adam/foodsoft#37]
The tests seem to have been updated about 10 months ago. This is a pity; it reduces code quality, stability and makes it easier to accept patches that 'break' the code.

Also, if the tests are actually running, we might want to plug them into [Travis CI](git@github.com:dokterbob/foodsoft.git) for automated testing of every branch. By the time we need to do that, create a ticket and assign it to me - I can setup the CI and we'll get nice green or red bars for every pull request.

**Comment by fsmanuel** [comment]
+1 for travis integration

**Comment by dokterbob** [comment]
@fsmanuel If you could check whether there are actually some tests to run and get back to be, I'll look into setting up Travis. (I have little experience in Ruby so will need some time to figure out how to properly run the tests, setup the database and all.)

**Comment by wvengen** [comment]
moved to foodcoops/foodsoft#120
