### ISSUE TITLE
Documented deployment strategy / Auto deploy setup

### ISSUE THREAD

**Issue by dokterbob** [foodcoop-adam/foodsoft#38]
As we'll be working with multiple devs on a single project in our spare time, it is important that there is some deployment automation so all the devs can update and rollback deploys on demand, with a few simple commands so there is little risk of human error.

**Comment by fsmanuel** [comment]
what do u mean? something like capistrano?

**Comment by dokterbob** [comment]
Yep. Something like that would be ideal - but it's not just technology I am talking about. There should be a well-documented workflow on how and where updates are made (GIT branches etc) and preferably some kind of CI (see my ticket about Travis) as well.

**Comment by fsmanuel** [comment]
+1 sounds great!

**Comment by wvengen** [comment]
Yes!! An option would be to make the servers run git, and add post commit hooks to deploy pushes.

**Comment by dokterbob** [comment]
No, it is better to have the servers run a production-ready CI like Jenkins which is made for these kind of tasks. Travis is not stable enough and in any case we don't want untested code to go in production.

My personal preferance though would be to have a few simple shell commands to explitly tag production releases and perform deploys or rollbacks. I have implemented similar things in a Django/Python environment but do not know what the best tools of trade are for RoR.
