### ISSUE TITLE
add on the spot consumption to member order

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#4]
When a member wants to buy something on the spot on the pick-up day, it would be useful to be able to easily add it to the member order. This would apply to dinner, drinks, snacks, stock articles, leftovers and perhaps more.

Ability to indicate:
- menu of supper (single choice? multiple choices? - like vegan)
- type of drinks and quantities
- cakes, snacks

Possible workflow
- identification of member
- select cafe purchases (meal, drinks, snacks)
- press "add to bill"
- [accept addition to bill by member (insert password of you profile???)]

**Comment by wvengen** [comment]
#159 would allow adding free-price items, which would enable adding on the spot consumptions. Creating a separate screen like described here would be nice, but is somewhat out of scope for now. If you'd find this really useful in practice, feel free to reopen.
