### ISSUE TITLE
Create milestones for issues

### ISSUE THREAD

**Issue by dokterbob** [foodcoop-adam/foodsoft#40]
In order to have some clear overview of what is happening and when it ought to be happening, I'd like to propose using milestones to manage the project. 

A lot of the issues here seem to be feature requests and some of the features are really broad whereas others are more vague. It would make sense to prioritize the features and other issues using milestones; some stuff needs to be fixed 'right now', other stuff can be worked on in the next milestones (i.e. release) and the rest of the stuff could go into a 'someday' milestone.

Not sure this is the ideal approach, just throwing in some ideas.

**Comment by fsmanuel** [comment]
+1
one more thing i would add is how we deal with the main repo and this fork. it feels, like this fork develops into a much more complex system than the original foodsoft projekt. my question is, how we can provide the great new features for the main repo and if the original foodsoft software would like to benefit from the activities in this fork.
@bennibu and @JuliusR what do u think about all that?

**Comment by wvengen** [comment]
Yes! There currently are some milestones (linked to real-life foodcoop-adam dates), it would be great to have a 'someday' milestone. Besides that, the urgent tag is used to prioritize.

@fsmanuel That's been on my mind. One idea is to use a plugin system so that features can be added without affecting the codebase. Not sure how smoothly that can be done in rails.

**Comment by dokterbob** [comment]
Sorry, I hadn't seen the milestones before. Maybe a GH issue (AJAX-related or something).

@wvengen @fsmanuel I think it is better to first find an absolute minimum function set and to refactor towards a more modular architecture along the way. Featurism should be your biggest fear here. ;)

I guess we should stay in close contact with the developer of the main fork and possibly even offer to maintain the code for him, as the last work on his branch seems to be several months ago. This would make it a lot easier for other people to work on this project in efficient collaboration.

**Comment by dokterbob** [comment]
I'm closing this as a 'Someday' milestone seems to have been created.
