### ISSUE TITLE
replace language abbreviation with country flag

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#43]
now in the interface there is an abbreviation of the language the software is displayed in.

"nl" for netherlands, "en" for english and "de" for german

solution proposal: replace language abbreviation with country flag icon

see also #23

**Comment by wvengen** [comment]
nice but not urgent

**Comment by wvengen** [comment]
Now that the language is in user-preferences, this is not so important anymore.
When using select2 for the language drop-down, this is easy http://ivaynberg.github.io/select2/select-2.1.html#templating
