### ISSUE TITLE
pay bill by member

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#44]
Pragmatic solution
- Search for member
  [- read amount and insert into pin machine]
  [- payment by member]
  press "balance to zero" (name of button change?)
  back to search field

show "pay membership fee" as well as "balance to zero" so it is visible which members did not pay the membershop vee and so the system activates the household (ordergroup) with a seperate 35 euro before processing payments of other costs

![screen shot 2013-06-02 at 2 50 03 pm](https://f.cloud.github.com/assets/3144698/596319/15a75ea2-cb83-11e2-86ef-c5540a78fc26.png)

**Comment by wvengen** [comment]
moved to foodcoops/foodsoft#7
