### ISSUE TITLE
change "account orders" into "pay suppliers"

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#45]
in the admin area change "account orders" under "finances" into "pay suppliers"

**Comment by wvengen** [comment]
Accounting orders does much more than that - it is also the place to enter the amounts received, and to redistribute them over members. We may want to split them as part of the "Workflows 1.0" milestone.

**Comment by wvengen** [comment]
For now, renamed to "receive". In the future we'd want to split it into receive and finance screens.
