### ISSUE TITLE
New repo structure

### ISSUE THREAD

**Issue by fsmanuel** [foodcoop-adam/foodsoft#48]
As a result of more developers joining the project and opening issues and pull request we should change some things.

First of all I miss a working master branch. At the moment everything happens in branches and it looks like the project is almost dead (if u miss to look at all the branches).
I'm not sure what is the best solution so here is my proposal (comments and suggestions are very welcome):
- rails3 branch should be master
  - [bennibu/foodsoft](https://github.com/bennibu/foodsoft) rails3 should be merged into the new master
  - [wvengen/foodsoft](https://github.com/wvengen/foodsoft) rails3 should be merged into the new master
- [bennibu/foodsoft](https://github.com/bennibu/foodsoft) master should be renamed into rails2
- foodcoop amsterdam should rename its production branch (foodcoop) into foodcoop-adam (or similar but more self-explanatory)
- the feature branches can stay as they are

we now have to decide where this should happen ([bennibu/foodsoft](https://github.com/bennibu/foodsoft), [wvengen/foodsoft](https://github.com/wvengen/foodsoft) or a new fork)

after the changes it makes sense to merge https://github.com/wvengen/foodsoft/pull/41 and https://github.com/wvengen/foodsoft/pull/36 and work on https://github.com/wvengen/foodsoft/issues/37 and https://github.com/wvengen/foodsoft/issues/38

i really like to see more and more people joining the project!

**Comment by fsmanuel** [comment]
i did what i suggested above in my fork.
[fsmanuel/foodsoft](https://github.com/fsmanuel/foodsoft/)

**Comment by wvengen** [comment]
Thanks @fsmanuel, that is really a great plan.

How we setup this all depends, I think, on our development workflow. Is there someone that wants to merge all into the main codebase? Then a personal repository and lots of pull requests would be great. It does require that this person has the time to do maintain this.
If we'd like several committers, then it might be an idea to setup a foodsoft organisation in github. Then either all developers get direct commit access, or there is a team of core developers that do merges, and forks with pull requests handled by them.
Perhaps each foodcoop that has local changes could either have a user repository, get their own project in the foodsoft organisation, or a branch in the foodsoft project (but that would give a lot of people commit access).

What do you think?

**Comment by fsmanuel** [comment]
i think that we should have a working and tested master branch where only a few can do the merges. we should use pull requests to merge the new features and develop them in branches. that way we can discuss which features are good for all foodcoops and merge tham into master. every foodcoop can develop there own features and merge them  into there own foodsoft branch (like ur foodcoop-adam branch) and merge the working master into there foodsoft branch as well.

**Comment by wvengen** [comment]
Great! What do you think of a [github organisation](https://github.com/blog/674-introducing-organizations)? It could bring some clarity.

**Comment by wvengen** [comment]
@dokterbob anything to add?

**Comment by fsmanuel** [comment]
i don't think that a github organisation is needed but it doesn't hurt so go for it.

**Comment by dokterbob** [comment]
GH organization is a great idea, call it foodsoft and the repo foodsoft. A lot of projects work that way - but it's important to involve the original author/maintainer as we don't want to claim/steal his baby. However, he is not currently actively maintaining the software - and we are.

As for @fsmanuel's suggestion: we should strive to have a clean 'official' repository where only a few people 'the core team' have push access, the master is always working (stable/tests pass) and branches are used for maintenance of legacy versions. (We should consider a version and deprecation policy as well, later.)

All foodcoop's will fork the main repo and fire pull requests back so there is a clear authority so (often tough) design decisions can be made quickly.

**Comment by fsmanuel** [comment]
@wvengen and @dokterbob who creates the GH organization? should i do it and use my fork (with the merges) as the foodsoft repo?

**Comment by dokterbob** [comment]
Yes.

You should be administrator and we just contributors, or something like 
that.

Your fork should be the master (rename before pushing should suffice in 
the new repo so the current master branch will effectively become a 
legacy branch/fork.

Then we should find a way to transfer the issues, somebody must have 
written a tool for that by now.

Lastly; the wiki is just another GIT repository so that it can be easily 
migrated.

**Comment by wvengen** [comment]
Just a short notice before I'll be away this weekend: it is possible to move a repository completely to an organisation - just one time though. That should move everything, including tickets.

**Comment by fsmanuel** [comment]
i pushed everything to the new organization: [foodcoops/foodsoft](https://github.com/foodcoops/foodsoft)
foodsoft was already taken so i named the organization to foodcoops

@bennibu, @wvengen, @dokterbob and me are ownsers of the new organization. but we should work with pull requests as well.

the issues import didn't worked like i expected (comments and pull requests didn't went into the new project) but i guess it's not a big deal, cause most of the issues are related to foodcoop amsterdam...
