### ISSUE TITLE
unsupervised payment terminal

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#5]
It would be great if users could pay themselves on the pickup day using a payment terminal (PIN/POS). After payment, the user's account would be credited with the amount.

This requires a payment terminal device linked to a computer that communicates with foodsoft:
- Sending the amount to the pin apparatus 
- Receiving confirmation of payment from PIN aparatus

workflow idea
- Identification of member (enter member number?)
  - (optionally enter amount to credit, which may be more than current order)
- [show amount on pin machine]
- PIN by member

To use the link, the provider has to certify the software the PIN aparatus communicates with. this costs about 700 euros according to CCV. I do not know if this is for 1 provider or 1 type of PIN machine. For one foodcoop this is a lot of money, for several foodcoops this is very do-able.

**Comment by wvengen** [comment]
moved to foodcoop-adam#94
