### ISSUE TITLE
differentiate between members based on membership phase

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#54]
differentiate between members who did not pay (not-activated), members who did pay (activated), members who have been assigned to a workgroup/task (alive) and members who are in rest (in rest) because they are not doing work (with reason).

not-activated members have to pay the membership fee before they can order
activated members can order for a certain period until they are starting a task (1 order or 1 month?)
working members can order
members "in rest" cannot order until "awoken"

linked to issue #53

**Comment by wvengen** [comment]
Cool idea!
