### ISSUE TITLE
enable translation of categories

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#56]
all the items in the software can be translated but the categories are only there in the language one creates them. when you switch language one still sees the categories in the same language.

how to make translating of categories possible?

**Comment by fsmanuel** [comment]
can you open an issue at [foodcoops/foodsoft](https://github.com/foodcoops/foodsoft/issues) and add the i18n milestone? it should have the labels bug and easy to fix.

**Comment by Cor-Jan** [comment]
i copied the issue to foodcoops/foodsoft but i cannot select any milestone or labels.  restricted acces?

**Comment by fsmanuel** [comment]
@Cor-Jan thx.
i added the milestone and added you to the members of the foodcoops organization. hope you can add milestones now.

**Comment by wvengen** [comment]
see foodcoops/foodsoft#160

**Comment by wvengen** [comment]
moved to upstream
