### ISSUE TITLE
import category tree based on standards

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#57]
Use world-wide standard for keeping track of categories. For structured notes, see the wiki on [Categories](https://github.com/foodcoops/foodsoft/wiki/Categories). [GPC](http://www.gs1.org/gsmp/kc/gpc/production) would be a contender, as well as [UNSPSC](https://en.wikipedia.org/wiki/UNSPSC).

**Comment by wvengen** [comment]
Depends on #30. The full UNSPSC would be too much to handle (almost single category per product), so some sort of automatic recognition of what categories make sense to present would be needed as well - for example Jonagold apples have the UNSPSC category 50301545 - _Food Beverage and Tobacco Products > Fresh fruits > Apples > Jonagold apples_. When there's only one type of Jonagold apples available, and the other fruits are 50305436 Perry pears, it makes sense to just display the _Food Beverage and Tobacco Products > Fresh fruits > Apples_ category.

**Comment by Cor-Jan** [comment]
even beter catorisation (AND FREE!) is GPC to view categorisation visually :www.gs1.org/1/productssolutions/gdsn/gpc/browser/index.html
to download " http://www.gs1.org/gsmp/kc/gpc/production

available XML and in 6 languages,
