### ISSUE TITLE
enable manually organizing categories

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#58]
at the moment categories are organized alphabetically which can be confusing because e.g. vegetables and fruit are very far apart from eachother so it cost more energy/time to find the product you want. 

solution proposition:
add a category organization function to the categories editor\

**Comment by wvengen** [comment]
scheduled for 4.1, see foodcoops/foodsoft#87

**Comment by wvengen** [comment]
fixed in feature/nested_categories, which is merged into feature-group_order_ajax-adam (renamed to beta)
