### ISSUE TITLE
add categorisation of suppliers in supplier overview

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#59]
at the moment all suppliers are mixed with no logic in order.
this is confusing and 

seperate wholesale, farmers, artisan producers and retail
create categories based on their productoffer (fruit, vegetables, cheese, meat)

describe shortly in their profile the products that every suppliers offers (sausages, goat cheese) and show in supplier overview)
differentiate which suppliers change product assortment regularly? makes it easier for uploading new productlists

**Comment by wvengen** [comment]
current order in upstream is: end date (ascending)
current order in uicleanup is: end date (ascending), then supplier name (ascending)
