### ISSUE TITLE
checkout order before taking home (shift + member)

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#6]
if an order has been picked/gathered (by member or as a shift), there can be mistakes in which products are gathered and taken home with the assumption those are the products that he or she ordered. to eliminate mistakes we could add functionality to check if the products are the right products and make shure that member do not forget to take all their products, and take the right products.

 workflow proposal
Identification of member (household]
[show list of products ordered en quantities]
check if (correct) products are there
in what amount
1. find products not in basket of member
2. replace wrong products
3. delete from list for products who are not available

**Comment by wvengen** [comment]
Part of the [current_orders plugin](https://github.com/foodcoop-adam/foodsoft/tree/beta/lib/foodsoft_current_orders).
