### ISSUE TITLE
delete whole product assortment of a single supplier in 1 click 

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#60]
delete whole product assortment in 1 click instead of 60 clicks with 3000 product assortment

if there are 3000 products in a productlist and a user wants to delete them he or she has to select 30 times the all products button (max per 100 products per screen)  and then select delete all.

**Comment by wvengen** [comment]
Temporary fix with page size of 500. Foodsoft is not meant to be used with more than a couple of hundreds of articles at this moment.
