### ISSUE TITLE
admin menu links dissappear on a slim screen and tablet

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#62]
the admin menu dissapear on a slim screen and tablet.

![screen shot 2013-05-29 at 1 45 57 pm](https://f.cloud.github.com/assets/3144698/578400/64888e3c-c855-11e2-8fe3-2c50150f3275.png)
![screen shot 2013-05-29 at 1 45 35 pm](https://f.cloud.github.com/assets/3144698/578401/6489dc6a-c855-11e2-9766-4dd103f89ed5.png)

**Comment by wvengen** [comment]
This is a feature of the bootstrap theme. When you press the button that appears when the width becomes small, a large menu collapses. Somehow it can be difficult to properly press the button. Investigation needed.

**Comment by wvengen** [comment]
Not being able to press nested navigation items fixed by b2f032ac8e7925adcb94ece7d3671e15748faac2.
