### ISSUE TITLE
separate the paying suppliers and checking-in product deliveries

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#64]
1. enter invoice  (done by admin if send by email before delivery/pickup, otherwise on the spot by check-in) 
2. add original invoice as file or picture
3. invoicenr
4. billing date
5. amount
6. charge deposit
7. debit deposit

insert prices and quantities per product on invoice
1. pragmatic checkin in  (with manual re-distribution over members as currently in the system)

![screen shot 2013-06-02 at 7 21 07 pm](https://f.cloud.github.com/assets/3144698/596597/d803f864-cba8-11e2-8c53-114d9e83b516.png)
![screen shot 2013-06-02 at 7 21 00 pm](https://f.cloud.github.com/assets/3144698/596598/d818b650-cba8-11e2-9d66-dbad4ce59575.png)
1. after admin
   compare invoice with delivered

**Comment by wvengen** [comment]
Main issue solved since the introduction of the receive screen.
