### ISSUE TITLE
support barcode scanning

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#7]
For checking in wholesale products and for checking out we could use barcode scanners 1D bar/ean codes or 2D QR codes to scan and make sure that the identification of a product is done fast and without mistakes.

1D ean barcode scanners are cheap, but not able to scan QR and other 2D codes. A 2D scanner is much more expensive. Another option is to use a phone 2D barcodes scanning software like NEO reader.
- 1D scanner: many act as an external keyboard. Ways to implement this in the website:
  - give barcode field initial focus on relevant pages, skip to next after one is scanned
  - detect barcode entry within certain timeslot and handle entry
  - program barcode scanner to give key combination to focus next barcode field (if supported)
- 2D scanner:
- Mobile phone: need mobile version of foodsoft with scanning software integration.

**Comment by Cor-Jan** [comment]
combined with #98

**Comment by wvengen** [comment]
When we'd support the popular Motorola [LS2208](http://www.motorolasolutions.com/US-EN/Business+Product+and+Services/Bar+Code+Scanning/Bar+Code+Scanners/General+Purpose+Scanners/LS2208_US-EN) scanner ([manual](http://www.cimco.com/docs/cimco_mdc-max/v6/en/files/Symbol_LS2208_Reference_Guide_5880807a.pdf)), that would probably cover most cases. It can be programmed to submit a sequence before and one after the scan, which could be a shortcut key that the web page detects.

**Comment by wvengen** [comment]
This would be a nice jQuery plugin to catch barcode events: [jquery-barcodelistener](https://code.google.com/p/jquery-barcodelistener/). And [this](http://www.webonweboff.com/tips/js/event_key_codes.aspx#instant-test) to find event codes.
