### ISSUE TITLE
[multiimport] add format with category on single line

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#70]
add function to retrieve categories from productlist if they are located as title above articlegroup instead of in the category column

![screen shot 2013-05-30 at 8 42 33 am](https://f.cloud.github.com/assets/3144698/583623/b5fd38f8-c8fa-11e2-924a-2a428cdb03ff.png)

**Comment by wvengen** [comment]
target branch `multiimport` - create a new import format for this supplier

**Comment by wvengen** [comment]
done for terrasana in sharedlists
