### ISSUE TITLE
[onlinepay] wrong page after failed iDEAL membership payment

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#74]
When a user pays its membership using online banking and it fails, he is returned to the payment page for a normal credit payment, where he can fill in the amount. He should be redirected back to the membership payment page instead, showing the error message.

**Comment by wvengen** [comment]
Can be cleanly solved after #81. At this moment, it is even impossible to detect whether a failed payment was a membership fee payment or a regular account deposit.
