### ISSUE TITLE
[selfsignup] welcome email after signup

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#78]
Send a welcome email when someone has become a member.

Within the email:
- a link to a screen to insert preferences on tasks
- a link to a screen to add members to their household
  - and an explanation of advantages of adding household members
- short explanation what to expect (and username/password for logging in?)

Ideally the contents of this email is editable by an admin.

Things that may also be interesting to add:
- What are your talents?
- Which of the tasks would you like best?
- What would you ideally like to contribute?
- When are you available?

**Comment by wvengen** [comment]
related issue: #68
