### ISSUE TITLE
[uicleanup] reorganize columns to be more user friendly

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#80]
(product)name, producer/brand name, unit, label (fair, organic), price;    [clear separation between "productinfo" columns and "ordering" columns (space and/or seperation marks]  missing units, amount, tolorance, subtotal

![screen shot 2013-07-05 at 12 59 02 pm](https://f.cloud.github.com/assets/3144698/753256/00f2a130-e562-11e2-81db-726461474fd2.png)

**Comment by wvengen** [comment]
Wow, that looks very good, I'm inspired!

**Comment by wvengen** [comment]
suggestions:
- let's swap the "unit" and "label" columns
- let's make it possible to enter quantity and tolerance by keyboard as well
- let's show how much has been ordered by all (request from different people), e.g.

![current_orders_bar](https://f.cloud.github.com/assets/503804/1465617/13e7d528-4564-11e3-8e68-3a7081bd1d77.png)

**Comment by wvengen** [comment]
@tg-x feel free to start on this! You can skip the label column for now, as that might require adding something to the database (or we could guess it from the order note and/or manufacturer name).

**Comment by wvengen** [comment]
@tg-x I've created a new branch [uicleanup-grouporder](https://github.com/foodcoop-adam/foodsoft/tree/uicleanup-grouporder) on foodcoop-adam where you can work on. Happy hacking! And if you need any answers or advice, please let me know.

**Comment by Cor-Jan** [comment]
i would show the total amount to be ordered and leave out the info about
how much still needs to be ordered.
it has more the energy of "yeah! there are already people who are ordering
of the 12 pack/2 kg"

it has less energy of "half cup empty" and more "half cut full"

**Comment by wvengen** [comment]
(discussion on remaining units bar moved to private mail thread; when we have final agreement, please report here)
in the meantime - let's stick to the original proposal (as the result will not be very much different)

**Comment by wvengen** [comment]
I'd really want this for next order cycle, and made a beginning in [uicleanup-new-grouporder](https://github.com/foodcoop-adam/foodsoft/tree/uicleanup-new-grouporder). I hope you don't mind, tg :o

![progress-units](https://f.cloud.github.com/assets/503804/1645385/346f7a04-58ff-11e3-82d2-48589cf17291.png)

**Comment by Cor-Jan** [comment]
ziet er goed uit!
het getal voor de progress bar vind ik alleen nog niet helemaal duidelijk.
niet de hoogste prioriteit maar wou het toch even zeggen

**Comment by wvengen** [comment]
We've come far enough for milestone Foodcoops-beta, let's do the additional columns for a new iteration.
