### ISSUE TITLE
set initial configuration by means of a form

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#88]
country
- standard language
- valuta (euro, dollar, etc)

Name of the foodcoop

Members payments
- set membership amount per household
- set margin (% on top of buying price)
- payment moment(s) en type(s)

Delivery
- Delivery/pickup location adress (zipcode, streetname, housenumber, addition) [with possibility for coordinates!]
- Contact person
- Telephone contactperson
- [Backup contact person]
- [Telephone backup contact person]

administration
- emailadress for invoices
- (adress for invoices?)

etc ( add at will)

**Comment by wvengen** [comment]
depending on foodcoops#24
