### ISSUE TITLE
visually support getting wholesale orders full

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#89]
At the moment the software only shows how many products are needed to fill the software. it is not clear how many is already ordered.

solution: show how much is ordered and how much until order full by means of:
(above old solution, below new solution) 

![screen shot 2013-08-01 at 11 37 03 am](https://f.cloud.github.com/assets/3144698/892829/07344346-fa8e-11e2-8199-e95fa3395273.png)

**Comment by Cor-Jan** [comment]
part of #80

**Comment by wvengen** [comment]
done!
