### ISSUE TITLE
cleanup i18n

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#9]
Begin 2013, foodsoft has been internationalised (meaning that all texts have been replaced by identifiers, and the texts have been associated with these identifiers) and translated to English. [simple_form](http://simple-form.plataformatec.com.br/) has been used to i18n form labels, and sometimes direct `t('simple_form.labels.foo.bar')` was used. Now these sometimes contain duplicates, and it would be useful to normalise the data, and also to move the strings to ActiveRecord's model i18n when possible. Special cases can remain in simple_form's i18n.

See commit 98b729eb7189f87cf745e800d5f076f8131ba06a for an example. Also see bennibu/foodsoft#84 (in particular [this comment](https://github.com/bennibu/foodsoft/issues/84#issuecomment-16720060))

**Comment by fsmanuel** [comment]
closed in favor of https://github.com/foodcoops/foodsoft/issues/137
