### ISSUE TITLE
enable payment immediately after ordering

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#90]
for one-time foodcoops (popup foodcoops) there is no ensurance that people will actually pickup their order. this could mean that these products have to be paid to the  suppliers but no consumer pays for them.

a solution is to enable payment immediately after ordering with iDEAL and different online payment solutions and when what the people are getting is different the difference can be solved on the spot by extra payment (PIN? cash) or afterwards by bankpayment to people who ordered

**Comment by wvengen** [comment]
We need:
1. _online payment after ordering_
2. _payment of the difference afterwards_ - already supported, member will always pay what's needed
3. _refunds when the member payed more than he received_ - can be done manually by looking at the financial transactions (sorted by account balance); an export to a banking system would be very welcome if this happens often

Let's focus in this ticket on (1), and open a new one for (3) when implementation has started.

**Comment by wvengen** [comment]
running in production on feature-group_order_ajax-adam (renamed to beta) for more than a month now
