### ISSUE TITLE
add link to dashboard to show/send to household members to check the products and amounts to order

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#91]
when a member of a ordergroup/household orders and would like to check with other members of the household/ordergroup if everything is there or stuff is missing/too  much ordered, he/she could want to send a link to the other members to check if everything is ordered what is needed/wanted to be ordered by everyone
(tip of one of the buyers of foodcoop ohm 2013

**Comment by wvengen** [comment]
Would you like to explain? (and put it in the main description, press "Edit")
