### ISSUE TITLE
Digital scale connection

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#93]
When the fresh products workflow is implemented (#17), it would be useful to be able to connect digitals scales to the system - so that we don't need to enter weights manually.

**Comment by wvengen** [comment]
- Use a programmable keyboard input device, pressing an accelerator key, then the weight.
  - **pro:** no foodsoft changes or additional software required
  - **con:** either hardware needs to support it, or need additional soft-/hardware
- On mobile, switch to measuring app, when finished switch back to browser (like Adyen payment)
  - **pro:** allow to fully embed measuring interface (incl. constant updates to weight)
  - **con:** need to create measurement app (Android+iOS), connect to foodsoft
  - **con:** switching apps takes time and breaks flow (could create custom app with embedded browser supporting input from scale directly to mitigate that)

**Comment by wvengen** [comment]
bluetooth electronic bench scale (serial protocol, sends bytes continuously)
http://www.alibaba.com/product-gs/850610346/stainless_steel_IP68_waterproof_bluetooth_bench.html

android app for bluetooth scale measurements, from supplier who seels them
http://www.appbrain.com/app/android-scale/elane.bt2.scale

rs232-bluetooth module, to connect rs232 scales
http://dx.com/p/rs232-bluetooth-serial-adapter-module-w-mini-usb-port-144177

**Comment by Cor-Jan** [comment]
is there a way to let the scale communicate with the online software without switching between app and foodsoft?

ps. i thought that adyen app was only needed for manual input, and that with hpp integration that it would directly communicate. if this is true, can we do this with the scale as well?

**Comment by wvengen** [comment]
@Cor-Jan yes, see updated comment with options. Regarding Adyen - yes hpp wouldn't need app, my bad.
