### ISSUE TITLE
Adyen PIN payment

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#94]
We'll be using Adyen shuttle PIN terminals, so we need to support them as payment provider.
- [x] credit ordergroup account after payment (using http callback from Adyen)
- [x] screen to specify user, and initiate payment
- [x] make interaction with Shuttle / mobile app work
- [x] allow to select online payment provider (module) for membership fee payment
- [x] wait for plugin support in foodsoft (foodcoops#194)
- [x] move plugin to main foodsoft-adam repository
- [x] load all ordergroups in mobile view
- [x] do not allow amount to go below zero
- [x] show whose account is below zero in ordergroup list (green background)
- [ ] show ui feedback when ordergroup/retry is pressed (while waiting on request)
- [x] don't open a new tab when returning from Adyen app to browser
- [ ] find out if it works in practice

n.b. iDEAL payments are for a next iteration

**Comment by wvengen** [comment]
Work has started on the onlinepay branch using a plugin `lib/foodsoft_adyen`.
We can still use Mollie for iDEAL, if we like (which has moved to a separate plugin `lib/foodsoft_mollie`).

**Comment by wvengen** [comment]
@Cor-Jan do we want to use Adyen's iDEAL when we can still use Mollie?

**Comment by Cor-Jan** [comment]
paytor is 43 cnts per transaction  (processing by mollie, normally 99 ct per transaction)
adyen is 60 ct per transaction but on the same payment platform.

switch to adyen is for easyness of use/overview. is a really important too.
i would say. switch to adyen. keeps it structured

**Comment by wvengen** [comment]
At this moment, when the `foodsoft_mollie` plugin is enabled, the membership fee can be paid using that. Since we want to be able to use other providers as well, we need a preference to specify which provider is used to do online payments. Added task for that in issue description.
If this is too much work, we can resort to using only one payment plugin for everything. A helper method could then check which plugin is enabled, and give the appropriate payment link. Or something like that.

**Comment by wvengen** [comment]
The Adyen PIN payment app works by intercepting the `adyen:///payment` url. The query string has parameters like `amount` to give payment details. There is also a callback url, where the user will be directed to after payment. Sounds easy!

Update: the Android app uses the `http://www.adyen.com/android-app/payment` url instead.

**Comment by wvengen** [comment]
After every transaction a new tab is created (when returning from the Adyen app). This is annoying. Possible solutions:
- Remember browser Intent so that the Adyen app returning always goes to the same tab - see [here](http://stackoverflow.com/questions/5489086/open-an-url-in-android-browser-avoid-multiple-tabs); still opens one new tab when returning for the first time and might need Adyen app to be changed.
- Set cookie on return. Original page uses `setTimeout` to read cookie, and if it's set - close the window.

**Comment by wvengen** [comment]
Fixed the issue of opening a new tab each time the Adyen app returns by creating an app - see [foodsoft-app-payment](https://github.com/wvengen-phonegap/foodsoft-app-payment), install from [here](https://build.phonegap.com/apps/738579/share) (after enabling apps from unknown sources, see [here](http://www.groovypost.com/howto/mobile/android-how-to-allow-install-apps-unknown-sources/) and [here](http://phandroid.com/2013/07/20/android-101-sideloading-apps/), for example).

**Comment by wvengen** [comment]
Mostly works, but as there were contractual issues, this is cancelled.
