### ISSUE TITLE
time and error reducing dividing (uses a barcode scanner)

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#98]
dividing products in wholesale packaging takes a lot of time and is a place where a lot of mistakes happen. to reduce the time spend on deviding products and reduce mistakes 
problems:
- pick the wrong product that looks like the product they are looking for but is a little different. 
- a lot of time is spend on organizing the products based on category to work easily from a list that is organized based on categorization

proposed solution: divide per single wholesale package using a barcode scanner

procedure:
1. get the first wholesale package from the pallet or container, 
2. scan a product in the package with barcode scanning 
and the software (in recieving screen) shows how much of this wholesale package to put in what member crate e.g. 2 pieces, crate nr 34
1. the member confirms putting it in 
   and the software shows the next action e.g. 5 pieces, crate nr 28

this until the end of the wholesale package 

then start again with new wholesale package

**Comment by wvengen** [comment]
Cool :) That would require a mobile interface with a barcode scanner. I propose to postpone this for a bit, and focus on working with printed lists for now.

**Comment by Cor-Jan** [comment]
now without barcode scanner

procedure:
1. get the first wholesale package from the pallet or container  
2. identify a product in the package (by means of selecting a nr of specific attributes? )

and the software (in recieving screen) prints a list with how much of this wholesale package to put in what member crate e.g. 
2 pieces, crate nr 34
5 pieces, crate nr 28
3 pieces, crate nr 103

then start again with new wholesale package

the idea behind this method of working is to save time putting the products into the members crates in a precise way without spending time on organizing the products per category and per product to count

**Comment by wvengen** [comment]
This is present in the order screen, "sort by articles", which displays a list of ordergroup amounts for each article.
- would be nice to be able to search for a product in that screen
- would be handy to have in a mobile website / app

**Comment by Cor-Jan** [comment]
that is not what i mean.

this is a way of working per wholesale package, not per product.
a order can contain multiple wholesale packages of the same product.

the most mistakes are made with products who look alike, 
thus if someone has a hangover, has her period or is just plain sloppy; this could be a method to reduce mistakes because people put wholesale packages of different products together (organic or biodynamic, different flavour and other small differences between products)
